// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of compiling a single document.
 */
export type CompileOutcome = { 
/**
 * `true` when compilation produced output with no errors.
 */
success: boolean, 
/**
 * Wall-clock compile duration in milliseconds.
 */
duration_ms: bigint, 
/**
 * Errors encountered (empty on success).
 */
errors: Array<Diagnostic>, };

/**
 * Lifecycle status of a compile, emitted on the `status` event.
 */
export type CompileStatus = "idle" | "compiling" | "success" | "error";

/**
 * Payload of the `compiled` event: one self-contained SVG string per page.
 */
export type CompiledPayload = { id: DocumentId, pages: Array<string>, 
/**
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the contract.
 */
durationMs: number, };

/**
 * A single diagnostic, IPC/serialization-friendly.
 */
export type Diagnostic = { severity: Severity, range: Range, message: string, 
/**
 * Typst error code, when available.
 */
code: bigint | null, };

/**
 * Payload of the `diagnostics` event.
 */
export type DiagnosticsPayload = { id: DocumentId, diagnostics: Array<Diagnostic>, };

/**
 * A single entry returned by [`read_dir`]: one child of a directory.
 */
export type DirEntry = { 
/**
 * Path relative to the workspace root, using `/` separators.
 * Empty string for the root itself.
 */
relative: string, 
/**
 * Entry name (last path component).
 */
name: string, kind: EntryKind, };

/**
 * Unique identifier for an open document (tab).
 *
 * Wraps a `Uuid` v4. Serialized as a string across IPC.
 */
export type DocumentId = string;

/**
 * Metadata for an open document tab. Independent of typst's own `Document`.
 */
export type DocumentMeta = { 
/**
 * Stable unique id for this tab.
 */
id: DocumentId, 
/**
 * Filesystem path, if backed by a file. `None` for unsaved/untitled docs.
 */
path: string | null, 
/**
 * Display title (filename or "Untitled").
 */
title: string, 
/**
 * Unsaved-changes flag.
 */
dirty: boolean, };

/**
 * Whether a tree entry is a file or a directory.
 */
export type EntryKind = "file" | "dir";

/**
 * Payload of the `fs_changed` event: paths (absolute) that changed on disk in
 * the workspace, detected by the filesystem watcher. The frontend refreshes
 * the affected parts of its file tree. Empty `paths` is a generic "something
 * changed, refresh" signal (used as a fallback).
 */
export type FsChangedPayload = { 
/**
 * Absolute paths that changed (created/modified/removed).
 */
paths: Array<string>, };

/**
 * Payload of the `lsp_status` event, emitted when the LSP connection
 * transitions (client connects / relay ends / tinymist exits). Lets the
 * frontend subscribe instead of polling `get_lsp_status`.
 */
export type LspStatusPayload = { running: boolean, wsUrl: string, available: boolean, };

/**
 * Response of `new_tab` / `open_file`: the tab's metadata paired with its
 * current source text, so the frontend can hydrate Monaco without re-reading
 * the file from disk.
 */
export type OpenedDocument = { content: string, 
/**
 * Stable unique id for this tab.
 */
id: DocumentId, 
/**
 * Filesystem path, if backed by a file. `None` for unsaved/untitled docs.
 */
path: string | null, 
/**
 * Display title (filename or "Untitled").
 */
title: string, 
/**
 * Unsaved-changes flag.
 */
dirty: boolean, };

/**
 * A 1-indexed text range (Monaco-friendly). Half-open `[start, end)`.
 */
export type Range = { start_line: number, start_column: number, end_line: number, end_column: number, };

/**
 * Severity of a diagnostic message.
 */
export type Severity = "Error" | "Warning" | "Info";

/**
 * Payload of the `status` event. `duration_ms` is present only on
 * `Success` / `Error`.
 */
export type StatusPayload = { id: DocumentId, status: CompileStatus, durationMs: number | null, };

/**
 * The currently open workspace, if any.
 */
export type WorkspaceMeta = { 
/**
 * Absolute path to the workspace root.
 */
root: string, 
/**
 * Display name (the root folder's basename).
 */
name: string, };
