// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `compare_recovery`: the snapshot buffer + the current disk content
 * (or `None` if the file is gone).
 */
export type CompareRecovery = { snapshot: string, disk?: string | null, };

/**
 * Result of compiling a single document.
 */
export type CompileOutcome = { 
/**
 * `true` when compilation produced output with no errors.
 */
success: boolean, 
/**
 * Wall-clock compile duration in milliseconds.
 */
duration_ms: bigint, 
/**
 * Errors encountered (empty on success).
 */
errors: Array<Diagnostic>, };

/**
 * Lifecycle status of a compile, emitted on the `status` event.
 */
export type CompileStatus = "idle" | "compiling" | "success" | "error";

/**
 * Payload of the `compiled` event: one self-contained SVG string per page,
 * plus a source map mapping each source line to its page-space bounding rect
 * (used by the frontend for scroll-sync and click-to-source).
 *
 * `revision` (§7) is the document content revision this compile corresponds
 * to. The frontend discards results whose revision is older than the tab's
 * current revision, so a slow compile can never overwrite a newer preview.
 */
export type CompiledPayload = { id: DocumentId, revision: number, pages: Array<string>, 
/**
 * Source line → preview-page bbox index, sorted by `(page, y)`. Empty for
 * documents with no rendered text (or when compilation produced no doc).
 */
lineMap: Array<LineRect>, 
/**
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the contract.
 */
durationMs: number, };

/**
 * Payload of the `conflict` event (§8.4): an external disk change to an open
 * document's file moved it into a conflict state. `disk_content` is present
 * for `Modified` so the UI can show a diff; absent otherwise.
 *
 * `revision` (§7) tags the buffer revision the conflict corresponds to.
 */
export type ConflictPayload = { id: DocumentId, revision: number, conflict: ConflictState, 
/**
 * The current disk content, present on `Modified` (so the UI can show a
 * diff). `None` for `None` / `Missing`.
 */
diskContent: string | null, };

/**
 * External-modification conflict state for a document (§5.4 / §8.4).
 *
 * Set by [`EditorService::handle_external_change`](crate::service::editor_service::EditorService::handle_external_change)
 * when a filesystem watcher reports a change to a document's backing file.
 * The user resolves a non-`None` state via explicit actions (use disk /
 * overwrite disk / Save As / discard); the resolution UI is out of scope for
 * the state-tracking layer — this enum is just the data.
 *
 * ## Wire format (§5.4 — string-tag only)
 *
 * On the wire this serializes as a **bare lowercase string** —
 * `"none" / "modified" / "missing" / "permission_changed" / "replaced"` — so
 * the frontend can keep treating `ConflictState` as a string-literal union.
 * The carried `disk_version` ([`Modified`]) and `identity_changed`
 * ([`Replaced`]) are Rust-side ONLY (kept in-memory for re-detection; not
 * serialized) — they are populated from disk reads, not from IPC. This keeps
 * the wire form backward-compatible with the pre-§5.4 frontend (which was a
 * 3-variant string union) and avoids a struct-per-variant churn.
 *
 * The serialization is hand-written (rather than `#[serde(rename_all=…)]`)
 * because serde's derive can't express "drop the variant's data and emit only
 * the tag" for a struct variant enum — `rename_all` would emit the tag for a
 * unit enum, but the moment `Modified` gains a field it becomes an internally
 * tagged struct on the wire. The custom [`serde::Serialize`] / [`serde::Deserialize`]
 * impls below give exactly the desired string-only shape, and [`tag`] / [`from_tag`]
 * are the single source of truth for the mapping.
 */
export type ConflictState = "none" | "modified" | "missing" | "permission_changed" | "replaced";

/**
 * A single diagnostic, IPC/serialization-friendly.
 */
export type Diagnostic = { severity: Severity, range: Range, message: string, 
/**
 * Typst error code, when available.
 */
code: bigint | null, };

/**
 * Payload of the `diagnostics` event. `revision` (§7) tags which buffer
 * revision the diagnostics correspond to.
 */
export type DiagnosticsPayload = { id: DocumentId, revision: number, diagnostics: Array<Diagnostic>, };

/**
 * A single entry returned by [`read_dir`]: one child of a directory.
 */
export type DirEntry = { 
/**
 * Path relative to the workspace root, using `/` separators.
 * Empty string for the root itself.
 */
relative: string, 
/**
 * Entry name (last path component).
 */
name: string, kind: EntryKind, };

/**
 * A snapshot of a file's on-disk content identity (§8.4).
 *
 * Two versions are equal iff their content hashes AND sizes match — i.e. the
 * bytes are (almost certainly) identical. The mtime is intentionally excluded
 * from equality so a `touch` (unchanged bytes, new mtime) compares equal.
 *
 * `Serialize`/`Deserialize` (added in the crash-recovery batch §5.1.2) lets a
 * [`RecoverySnapshot`](crate::persistence::recovery::RecoverySnapshot) record
 * the disk version the snapshot was captured against, so startup recovery can
 * tell whether the disk changed between snapshot capture and the next launch
 * (§5.1.3 "当前磁盘是否变化").
 */
export type DiskVersion = { 
/**
 * Hash of the file bytes (non-crypto, fast). Combined with `size` below it
 * uniquely identifies the content for change-detection purposes.
 */
content_hash: number, 
/**
 * Byte length of the file. Carried alongside the hash so a collision plus
 * a length mismatch still flags a change (belt-and-suspenders).
 */
size: number, };

/**
 * Unique identifier for an open document.
 *
 * Wraps a `Uuid` v4. Serialized as a string across IPC. Stable for the
 * document's entire open lifetime — origin transitions (Untitled → save,
 * WorkspaceFile ↔ LooseFile) preserve the id.
 */
export type DocumentId = string;

/**
 * Metadata for an open document. Independent of typst's own `Document`.
 *
 * `path` and `title` are retained as convenience fields derived from
 * [`DocumentOrigin`] for IPC consumers; the authoritative classification is
 * `origin`.
 */
export type DocumentMeta = { 
/**
 * Stable unique id for this document (preserved across origin transitions).
 */
id: DocumentId, 
/**
 * Filesystem path, if backed by a file. `None` for untitled docs.
 * Derived from [`DocumentOrigin::canonical_path`].
 */
path: string | null, 
/**
 * Display title (filename or "Untitled").
 */
title: string, 
/**
 * Unsaved-changes flag.
 */
dirty: boolean, 
/**
 * Origin classification (§4.2). Drives resolution / watching / LSP.
 */
origin: DocumentOrigin, 
/**
 * Monotonic content revision. Bumped on every `update_text`. Carried by
 * compile/diagnostics/status events so stale results can be discarded.
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the wire format.
 */
revision: number, 
/**
 * External-modification conflict state (§8.4). `None` when in sync with
 * disk; `Modified` / `Missing` when the watcher detected an external disk
 * change that could not be auto-applied (dirty buffer / deleted file).
 */
conflict: ConflictState, };

/**
 * How a document is anchored on disk (§4.2).
 *
 * Drives relative-resource resolution (`#include`, `#image()`), file
 * watching, and LSP folder association. Transitions between variants
 * preserve the [`DocumentId`].
 */
export type DocumentOrigin = { "kind": "untitled" } | { "kind": "workspaceFile", 
/**
 * Canonical absolute path of the file.
 */
path: string, 
/**
 * Owning workspace. Used to re-classify on workspace open/close.
 */
workspace_id: WorkspaceId, } | { "kind": "looseFile", 
/**
 * Canonical absolute path of the file.
 */
path: string, 
/**
 * Resolution root: the file's parent directory.
 */
root: string, };

/**
 * Whether a tree entry is a file or a directory.
 */
export type EntryKind = "file" | "dir";

/**
 * A stable, machine-readable error code (§5.3).
 *
 * The frontend branches on this instead of parsing a message string. Serialized
 * as `snake_case` so the wire value (`"permission_denied"`) matches the
 * generated TypeScript literal union.
 */
export type ErrorCode = "permission_denied" | "read_only" | "disk_full" | "target_missing" | "parent_missing" | "path_occupied" | "external_conflict" | "already_open" | "invalid_path" | "io_transient" | "not_found" | "invalid_input" | "compile" | "export" | "cancelled" | "other";

/**
 * Payload of the `focus_view` event (§6.1): the frontend activates the tab
 * for `id`. Reuses the existing DocumentId type so it is already on the wire.
 */
export type FocusViewPayload = { id: DocumentId, };

/**
 * Payload of the `fs_changed` event: paths (absolute) that changed on disk in
 * the workspace, detected by the filesystem watcher. The frontend refreshes
 * the affected parts of its file tree. Empty `paths` is a generic "something
 * changed, refresh" signal (used as a fallback).
 */
export type FsChangedPayload = { 
/**
 * Absolute paths that changed (created/modified/removed).
 */
paths: Array<string>, };

/**
 * Structured IPC error (§5.3: `{ code, message, details?, recoverable }`).
 *
 * Serialized as a JSON **object** (not a string) so the frontend can branch on
 * `code`. Field names are `camelCase` to match the generated TypeScript.
 */
export type IpcError = { 
/**
 * Stable machine-readable code — branch on this in the frontend.
 */
code: ErrorCode, 
/**
 * Human-readable message (locale-independent, English). Safe to surface.
 */
message: string, 
/**
 * Optional structured details (e.g. `AlreadyOpen` carries the existing id
 * and path so the caller can focus that view). Omitted when `None`. Typed
 * as a permissive `unknown` on the wire (shape varies by code).
 */
details: unknown | null, 
/**
 * Whether the caller can reasonably retry / recover. `false` for hard
 * failures (permission, not-found); `true` for transient ones (the
 * frontend may offer a Retry button).
 */
recoverable: boolean, };

/**
 * A source line's bounding rectangle on a preview page.
 *
 * `page` is 0-indexed; `line` is 1-indexed (matching Monaco). Geometry is in
 * points, relative to the page's top-left corner.
 */
export type LineRect = { 
/**
 * 1-indexed source line.
 */
line: number, 
/**
 * 0-indexed page number.
 */
page: number, 
/**
 * Left edge of the line's bounding box, in pt.
 */
x: number, 
/**
 * Top edge of the line's bounding box, in pt.
 */
y: number, 
/**
 * Width of the bounding box, in pt.
 */
w: number, 
/**
 * Height of the bounding box, in pt.
 */
h: number, };

/**
 * Payload of the `lsp_status` event, emitted when the LSP connection
 * transitions (client connects / relay ends / tinymist exits). Lets the
 * frontend subscribe instead of polling `get_lsp_status`.
 */
export type LspStatusPayload = { running: boolean, wsUrl: string, available: boolean, };

/**
 * A single open-document entry in the persisted session. The frontend
 * assembles this in display order from its tab list.
 *
 * Variants are deliberately coarse (`Disk` vs `Untitled`): the
 * workspace-file vs loose-file distinction is a *derived* classification
 * recomputed on restore (§4.3), so it is not stored. `dirty` is carried so a
 * restore can re-mark a document (for disk files, a dirty record means "you
 * had unsaved edits at shutdown that are now lost" — see the restore path).
 */
export type OpenDocRecord = { "kind": "disk", path: string, dirty: boolean, } | { "kind": "untitled", content: string, dirty: boolean, };

/**
 * Payload of the `open_external_file` event (§6.1): the frontend opens a new
 * tab at the absolute `path` via the existing `openFileByPath` flow.
 */
export type OpenExternalFilePayload = { path: string, };

/**
 * Response of `new_tab` / `open_file`: the tab's metadata paired with its
 * current source text, so the frontend can hydrate Monaco without re-reading
 * the file from disk.
 */
export type OpenedDocument = { content: string, 
/**
 * Stable unique id for this document (preserved across origin transitions).
 */
id: DocumentId, 
/**
 * Filesystem path, if backed by a file. `None` for untitled docs.
 * Derived from [`DocumentOrigin::canonical_path`].
 */
path: string | null, 
/**
 * Display title (filename or "Untitled").
 */
title: string, 
/**
 * Unsaved-changes flag.
 */
dirty: boolean, 
/**
 * Origin classification (§4.2). Drives resolution / watching / LSP.
 */
origin: DocumentOrigin, 
/**
 * Monotonic content revision. Bumped on every `update_text`. Carried by
 * compile/diagnostics/status events so stale results can be discarded.
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the wire format.
 */
revision: number, 
/**
 * External-modification conflict state (§8.4). `None` when in sync with
 * disk; `Modified` / `Missing` when the watcher detected an external disk
 * change that could not be auto-applied (dirty buffer / deleted file).
 */
conflict: ConflictState, };

/**
 * A 1-indexed text range (Monaco-friendly). Half-open `[start, end)`.
 */
export type Range = { start_line: number, start_column: number, end_line: number, end_column: number, };

/**
 * One recoverable document surfaced to the UI at startup (§5.1.3). The backend
 * computes `disk_changed` by comparing the snapshot's recorded disk version to
 * the file's current on-disk version, so the UI can decide the default action
 * (recover the buffer vs. must-compare).
 */
export type RecoverableInfo = { 
/**
 * The document id from the snapshot (a uuid string).
 */
documentId: string, title: string, 
/**
 * Canonical disk path, `None` for an Untitled snapshot.
 */
canonicalPath?: string | null, 
/**
 * Unix-millis capture timestamp.
 */
capturedAt: number, 
/**
 * True iff the disk file's current content differs from the version the
 * snapshot was captured against (or the file is missing). Drives the
 * "must compare" default for disk-changed docs (§5.1.3).
 */
diskChanged: boolean, };

/**
 * Response of the `recover_document` IPC: enough to rebuild an in-memory
 * document from a snapshot WITHOUT writing disk (§5.1.3 "恢复只创建内存文档").
 */
export type RecoveredDocument = { documentId: string, 
/**
 * The unsaved buffer content from the snapshot.
 */
content: string, title: string, canonicalPath?: string | null, 
/**
 * Origin tag (`"untitled"` / `"workspace"` / `"loose"`).
 */
origin: string, };

/**
 * Payload of the `recovery_available` event (§5.1.3): emitted once at startup
 * when recoverable snapshots exist (no clean-shutdown marker, or a snapshot
 * newer than disk). The frontend shows a `RecoveryDialog` with one row per
 * snapshot.
 */
export type RecoveryAvailablePayload = { snapshots: Array<RecoverableInfo>, };

/**
 * One entry in a [`SaveAllResult`]'s `failed` list.
 */
export type SaveAllFailure = { id: DocumentId, error: IpcError | null, };

/**
 * Per-document result of a [`SaveCoordinator::save_all`] batch.
 */
export type SaveAllResult = { 
/**
 * Ids saved successfully in this batch.
 */
saved: Array<DocumentId>, 
/**
 * Ids that failed or were skipped (because an earlier id failed/cancelled).
 * Each carries the structured error for the first failure; the rest are
 * `unreached` (no attempt made).
 */
failed: Array<SaveAllFailure>, };

/**
 * Per-document save state machine (§5.3). Emitted on every transition via the
 * `save_state_changed` Tauri event; the frontend mirrors it for the status bar
 * (saving indicator / red save-failed state).
 */
export type SaveState = "idle" | { "saving": { revision: number, } } | { "saved": { revision: number, } } | { "failed": { revision: number, code: ErrorCode, message: string, } };

/**
 * Payload of the `save_state_changed` event: the new save state for `id`.
 */
export type SaveStateChangedPayload = { id: DocumentId, state: SaveState, };

/**
 * What we remember between launches. All fields default so an OLD session.json
 * (with only `lastWorkspace`/`lastFile`) still loads cleanly.
 *
 * `rename_all = "camelCase"` so the on-disk shape matches what the frontend
 * sends in a `save_session` patch (`openDocuments`, `activeDocumentId`, …) and
 * what older builds wrote (`lastWorkspace`/`lastFile`). Without it serde would
 * look for snake_case keys and silently drop every camelCase field.
 */
export type Session = { 
/**
 * Session schema version (§7.3). Defaults to the current version on
 * fresh writes; on load, an absent field deserializes to `0` (treated as
 * "version unknown / pre-versioning") and is migrated up to
 * [`CURRENT_SCHEMA_VERSION`] by [`session_migrator`] before use. The
 * frontend never needs to send this — it's a backend-managed tag.
 */
schemaVersion: number, 
/**
 * Absolute path of the last workspace folder, or "".
 *
 * The `alias` lets us read **real legacy `session.json` files** written
 * by older builds, which serialized in snake_case (no `rename_all` then).
 * Without it, those files would silently default to "" on upgrade and the
 * user's remembered workspace would stop reopening.
 */
lastWorkspace: string, 
/**
 * Absolute path of the last file, or "". Kept for backward-compat with
 * older session.json files; superseded by `open_documents`. Same alias
 * story as `last_workspace`.
 */
lastFile: string, 
/**
 * Every open document, in display (tab) order. See [`OpenDocRecord`].
 */
openDocuments: Array<OpenDocRecord>, 
/**
 * The active view's document id (as a string). May reference a doc that
 * fails to restore; the caller falls back to the last successfully opened
 * view in that case.
 */
activeDocumentId: string | null, };

/**
 * Severity of a diagnostic message.
 */
export type Severity = "Error" | "Warning" | "Info";

/**
 * A single non-fatal failure observed during startup.
 */
export type StartupProblem = { 
/**
 * The component that failed (e.g. `"config_dir"`, `"settings"`, `"session"`).
 */
component: string, 
/**
 * A short human-readable message (no document text — §7.4).
 */
message: string, };

/**
 * Payload of the `startup_problems` event (§6.5). Emitted once at end of
 * setup only when `problems` is non-empty.
 */
export type StartupProblemsPayload = { problems: Array<StartupProblem>, };

/**
 * Payload of the `status` event. `duration_ms` is present only on
 * `Success` / `Error`. `revision` (§7) tags the buffer revision.
 */
export type StatusPayload = { id: DocumentId, revision: number, status: CompileStatus, durationMs: number | null, };

/**
 * Identifier for the currently active workspace (§4.2 / §4.3).
 *
 * Owned by `WorkspaceService`; embedded in [`DocumentOrigin::WorkspaceFile`]
 * so a document knows which workspace owns it. When a workspace closes, its
 * `WorkspaceFile`s become `LooseFile`s, dropping this id.
 */
export type WorkspaceId = string;

/**
 * The currently open workspace, if any.
 */
export type WorkspaceMeta = { 
/**
 * Absolute path to the workspace root.
 */
root: string, 
/**
 * Display name (the root folder's basename).
 */
name: string, };
