// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of compiling a single document.
 */
export type CompileOutcome = { 
/**
 * `true` when compilation produced output with no errors.
 */
success: boolean, 
/**
 * Wall-clock compile duration in milliseconds.
 */
duration_ms: bigint, 
/**
 * Errors encountered (empty on success).
 */
errors: Array<Diagnostic>, };

/**
 * Lifecycle status of a compile, emitted on the `status` event.
 */
export type CompileStatus = "idle" | "compiling" | "success" | "error";

/**
 * Payload of the `compiled` event: one self-contained SVG string per page,
 * plus a source map mapping each source line to its page-space bounding rect
 * (used by the frontend for scroll-sync and click-to-source).
 *
 * `revision` (§7) is the document content revision this compile corresponds
 * to. The frontend discards results whose revision is older than the tab's
 * current revision, so a slow compile can never overwrite a newer preview.
 */
export type CompiledPayload = { id: DocumentId, revision: number, pages: Array<string>, 
/**
 * Source line → preview-page bbox index, sorted by `(page, y)`. Empty for
 * documents with no rendered text (or when compilation produced no doc).
 */
lineMap: Array<LineRect>, 
/**
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the contract.
 */
durationMs: number, };

/**
 * A single diagnostic, IPC/serialization-friendly.
 */
export type Diagnostic = { severity: Severity, range: Range, message: string, 
/**
 * Typst error code, when available.
 */
code: bigint | null, };

/**
 * Payload of the `diagnostics` event. `revision` (§7) tags which buffer
 * revision the diagnostics correspond to.
 */
export type DiagnosticsPayload = { id: DocumentId, revision: number, diagnostics: Array<Diagnostic>, };

/**
 * A single entry returned by [`read_dir`]: one child of a directory.
 */
export type DirEntry = { 
/**
 * Path relative to the workspace root, using `/` separators.
 * Empty string for the root itself.
 */
relative: string, 
/**
 * Entry name (last path component).
 */
name: string, kind: EntryKind, };

/**
 * Unique identifier for an open document.
 *
 * Wraps a `Uuid` v4. Serialized as a string across IPC. Stable for the
 * document's entire open lifetime — origin transitions (Untitled → save,
 * WorkspaceFile ↔ LooseFile) preserve the id.
 */
export type DocumentId = string;

/**
 * Metadata for an open document. Independent of typst's own `Document`.
 *
 * `path` and `title` are retained as convenience fields derived from
 * [`DocumentOrigin`] for IPC consumers; the authoritative classification is
 * `origin`.
 */
export type DocumentMeta = { 
/**
 * Stable unique id for this document (preserved across origin transitions).
 */
id: DocumentId, 
/**
 * Filesystem path, if backed by a file. `None` for untitled docs.
 * Derived from [`DocumentOrigin::canonical_path`].
 */
path: string | null, 
/**
 * Display title (filename or "Untitled").
 */
title: string, 
/**
 * Unsaved-changes flag.
 */
dirty: boolean, 
/**
 * Origin classification (§4.2). Drives resolution / watching / LSP.
 */
origin: DocumentOrigin, 
/**
 * Monotonic content revision. Bumped on every `update_text`. Carried by
 * compile/diagnostics/status events so stale results can be discarded.
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the wire format.
 */
revision: number, };

/**
 * How a document is anchored on disk (§4.2).
 *
 * Drives relative-resource resolution (`#include`, `#image()`), file
 * watching, and LSP folder association. Transitions between variants
 * preserve the [`DocumentId`].
 */
export type DocumentOrigin = { "kind": "untitled" } | { "kind": "workspaceFile", 
/**
 * Canonical absolute path of the file.
 */
path: string, 
/**
 * Owning workspace. Used to re-classify on workspace open/close.
 */
workspace_id: WorkspaceId, } | { "kind": "looseFile", 
/**
 * Canonical absolute path of the file.
 */
path: string, 
/**
 * Resolution root: the file's parent directory.
 */
root: string, };

/**
 * Whether a tree entry is a file or a directory.
 */
export type EntryKind = "file" | "dir";

/**
 * Payload of the `fs_changed` event: paths (absolute) that changed on disk in
 * the workspace, detected by the filesystem watcher. The frontend refreshes
 * the affected parts of its file tree. Empty `paths` is a generic "something
 * changed, refresh" signal (used as a fallback).
 */
export type FsChangedPayload = { 
/**
 * Absolute paths that changed (created/modified/removed).
 */
paths: Array<string>, };

/**
 * A source line's bounding rectangle on a preview page.
 *
 * `page` is 0-indexed; `line` is 1-indexed (matching Monaco). Geometry is in
 * points, relative to the page's top-left corner.
 */
export type LineRect = { 
/**
 * 1-indexed source line.
 */
line: number, 
/**
 * 0-indexed page number.
 */
page: number, 
/**
 * Left edge of the line's bounding box, in pt.
 */
x: number, 
/**
 * Top edge of the line's bounding box, in pt.
 */
y: number, 
/**
 * Width of the bounding box, in pt.
 */
w: number, 
/**
 * Height of the bounding box, in pt.
 */
h: number, };

/**
 * Payload of the `lsp_status` event, emitted when the LSP connection
 * transitions (client connects / relay ends / tinymist exits). Lets the
 * frontend subscribe instead of polling `get_lsp_status`.
 */
export type LspStatusPayload = { running: boolean, wsUrl: string, available: boolean, };

/**
 * Response of `new_tab` / `open_file`: the tab's metadata paired with its
 * current source text, so the frontend can hydrate Monaco without re-reading
 * the file from disk.
 */
export type OpenedDocument = { content: string, 
/**
 * Stable unique id for this document (preserved across origin transitions).
 */
id: DocumentId, 
/**
 * Filesystem path, if backed by a file. `None` for untitled docs.
 * Derived from [`DocumentOrigin::canonical_path`].
 */
path: string | null, 
/**
 * Display title (filename or "Untitled").
 */
title: string, 
/**
 * Unsaved-changes flag.
 */
dirty: boolean, 
/**
 * Origin classification (§4.2). Drives resolution / watching / LSP.
 */
origin: DocumentOrigin, 
/**
 * Monotonic content revision. Bumped on every `update_text`. Carried by
 * compile/diagnostics/status events so stale results can be discarded.
 * `u64` maps to `bigint` by default in ts-rs, but Tauri serializes it as a
 * JSON number at runtime — override to `number` to match the wire format.
 */
revision: number, };

/**
 * A 1-indexed text range (Monaco-friendly). Half-open `[start, end)`.
 */
export type Range = { start_line: number, start_column: number, end_line: number, end_column: number, };

/**
 * Severity of a diagnostic message.
 */
export type Severity = "Error" | "Warning" | "Info";

/**
 * Payload of the `status` event. `duration_ms` is present only on
 * `Success` / `Error`. `revision` (§7) tags the buffer revision.
 */
export type StatusPayload = { id: DocumentId, revision: number, status: CompileStatus, durationMs: number | null, };

/**
 * Identifier for the currently active workspace (§4.2 / §4.3).
 *
 * Owned by `WorkspaceService`; embedded in [`DocumentOrigin::WorkspaceFile`]
 * so a document knows which workspace owns it. When a workspace closes, its
 * `WorkspaceFile`s become `LooseFile`s, dropping this id.
 */
export type WorkspaceId = string;

/**
 * The currently open workspace, if any.
 */
export type WorkspaceMeta = { 
/**
 * Absolute path to the workspace root.
 */
root: string, 
/**
 * Display name (the root folder's basename).
 */
name: string, };
