// Frontend-only UI types. NOT generated by ts-rs.
// Domain/IPC types (DocumentId, Diagnostic, Severity, Range, OpenedDocument,
// DirEntry, EntryKind, WorkspaceMeta, FsChangedPayload, LspStatusPayload,
// LspStatusKind, LspRestartReason, ...) live in ./types and are auto-generated
// by ts-rs — do not duplicate here.

// Re-export the wire payload types so existing `from "./ui-types"` import
// sites keep resolving. These used to be hand-maintained mirrors of the
// ts-rs output; re-exporting removes the manual lockstep duty.
export type {
  LspStatusPayload,
  LspStatusKind,
  LspRestartReason,
  CompileStatus,
  CompiledPayload,
  DiagnosticsPayload,
  StatusPayload,
} from "./types";

/**
 * Payload of the `menu_event` event: a native menu item was activated. The
 * `id` matches the menu ids defined in the Rust `ipc::menu::ids` module. For
 * check items (toggle-sidebar/toggle-preview), `checked` is the new state.
 */
export interface MenuEventPayload {
  id: string;
  checked: boolean;
}
