// Frontend-only UI types. NOT generated by ts-rs.
// Domain/IPC types (DocumentId, Diagnostic, Severity, Range, OpenedDocument,
// DirEntry, EntryKind, WorkspaceMeta, FsChangedPayload, ...) live in ./types
// and are auto-generated by ts-rs — do not duplicate here.

import type { Diagnostic, DocumentId, LineRect } from "./types";

/**
 * Frontend compile lifecycle for a single tab. Drives the StatusBar label.
 * Sent over the `status` event by the Rust backend.
 */
export type CompileStatus = "idle" | "compiling" | "success" | "error";

/** Payload of the `compiled` event (svg pages + source map) from the backend. */
export interface CompiledPayload {
  id: DocumentId;
  /**
   * Document content revision this compile corresponds to (§7). If it is
   * strictly less than the tab's current `revision`, the result is stale and
   * must be discarded — a newer edit already won.
   */
  revision: number;
  pages: string[];
  /** Source line → preview-page bbox index (scroll-sync / click-to-source). */
  lineMap: LineRect[];
  durationMs: number;
}

/** Payload of the `diagnostics` event emitted by the Rust backend. */
export interface DiagnosticsPayload {
  id: DocumentId;
  /** Document content revision these diagnostics correspond to (§7). */
  revision: number;
  diagnostics: Diagnostic[];
}

/** Payload of the `status` event emitted by the Rust backend. */
export interface StatusPayload {
  id: DocumentId;
  /** Document content revision this status corresponds to (§7). */
  revision: number;
  status: CompileStatus;
  durationMs?: number;
}

/** Payload of the `lsp_status` event (LSP connection transitions). */
export interface LspStatusPayload {
  running: boolean;
  wsUrl: string;
  available: boolean;
}

/**
 * Payload of the `menu_event` event: a native menu item was activated. The
 * `id` matches the menu ids defined in the Rust `ipc::menu::ids` module. For
 * check items (toggle-sidebar/toggle-preview), `checked` is the new state.
 */
export interface MenuEventPayload {
  id: string;
  checked: boolean;
}
