// Frontend-only UI types. NOT generated by ts-rs.
// Domain/IPC types (DocumentId, Diagnostic, Severity, Range, OpenedDocument,
// DirEntry, EntryKind, WorkspaceMeta, FsChangedPayload, LspStatusPayload,
// LspStatusKind, LspRestartReason, ...) live in ./types and are auto-generated
// by ts-rs — do not duplicate here.

import type {
  ChangedPage,
  Diagnostic,
  DocumentId,
  LineRect,
  OutlineNode,
} from "./types";

// Re-export the wire types so existing `from "./ui-types"` import sites keep
// resolving after the LSP payload moved to the generated `types.ts` (Task 7).
export type {
  LspStatusPayload,
  LspStatusKind,
  LspRestartReason,
  ChangedPage,
  CompiledPayload as GeneratedCompiledPayload,
} from "./types";

/**
 * Frontend compile lifecycle for a single tab. Drives the StatusBar label.
 * Sent over the `status` event by the Rust backend.
 *
 * `slow` (§6.2) is emitted while a compile has run past the slow-compile
 * threshold; a terminal `success`/`error` follows.
 */
export type CompileStatus = "idle" | "compiling" | "slow" | "success" | "error";

/**
 * Payload of the `compiled` event. Mirrors the ts-rs-generated
 * `CompiledPayload` in `types.ts`; duplicated here so existing import sites
 * (`from "./ui-types"`) keep resolving. Kept in lockstep — when the backend
 * struct changes, regenerate types.ts and update this mirror.
 *
 * Incremental rendering (§perf): when `full` is false, `changedPages` holds
 * ONLY the pages that changed since the previous compile; the frontend merges
 * them into its existing array, leaving unchanged pages' SVG string references
 * intact so `SvgPage`'s `memo` skips blob rebuild. When `full` is true, every
 * page is in `changedPages` and the frontend replaces its whole array.
 */
export interface CompiledPayload {
  id: DocumentId;
  /** Document content revision this compile corresponds to (§7). */
  revision: number;
  /** Total page count; the frontend sizes its array to this. */
  pageCount: number;
  /** true = full payload (every page in changedPages); false = incremental. */
  full: boolean;
  /** Pages rendered this round, each with its 0-based index. */
  changedPages: ChangedPage[];
  /** Source line → preview-page bbox index (scroll-sync / click-to-source). */
  lineMap: LineRect[];
  /** Document heading outline (§Outline view). Empty if no headings. */
  outline: OutlineNode[];
  durationMs: number;
}

/** Payload of the `diagnostics` event emitted by the Rust backend. */
export interface DiagnosticsPayload {
  id: DocumentId;
  /** Document content revision these diagnostics correspond to (§7). */
  revision: number;
  diagnostics: Diagnostic[];
}

/** Payload of the `status` event emitted by the Rust backend. */
export interface StatusPayload {
  id: DocumentId;
  /** Document content revision this status corresponds to (§7). */
  revision: number;
  status: CompileStatus;
  durationMs?: number;
}

/**
 * Payload of the `menu_event` event: a native menu item was activated. The
 * `id` matches the menu ids defined in the Rust `ipc::menu::ids` module. For
 * check items (toggle-sidebar/toggle-preview), `checked` is the new state.
 */
export interface MenuEventPayload {
  id: string;
  checked: boolean;
}
